# Файл оставлен как пример, так как docker-compose использует стандартную конфигурацию образа.
# Для обычного пакетного развёртывания ManticoreSearch можно адаптировать этот конфиг.

searchd {
    listen = 9306:mysql41
    listen = 9308:http
    log = /var/log/manticore/searchd.log
    query_log = /var/log/manticore/query.log
    pid_file = /var/run/manticore/searchd.pid
    data_dir = /var/lib/manticore
}
